// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OeeDashboardApi.Models;

#nullable disable

namespace oeeDashboardApi.Migrations
{
    [DbContext(typeof(OEEContext))]
    [Migration("20240726012742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OeeDashboardApi.Models.OEERecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Availability")
                        .HasColumnType("REAL");

                    b.Property<double>("Performance")
                        .HasColumnType("REAL");

                    b.Property<double>("Quality")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("OEERecords");
                });
#pragma warning restore 612, 618
        }
    }
}
